name: Teste Versionamento PR

on:
  pull_request:
    types: [closed]
    branches:
      - develop
      - 'release/*'
      - main

jobs:
  run-versioning:
    # SÃ³ roda se o PR foi realmente mergeado
    if: github.event.pull_request.merged == true
    uses: alexottonizup/git-flow-templates/.github/workflows/template-version.yml@join_version
    with:
      base_ref: ${{ github.event.pull_request.base.ref }}
      head_ref: ${{ github.event.pull_request.head.ref }}
    secrets:
      token: ${{ secrets.GH_TOKEN }}